### ISSUE TITLE
Cannot read property 'toLocaleLowerCase' of undefined at insertparamstx

### ISSUE THREAD

**Issue by indriApollo** [indriApollo/vormleer#1]
```
Jan 08 21:34:14 vps144761.ovh.net vormleerd[22341]: POST request for /verbs/amare
Jan 08 21:34:14 vps144761.ovh.net vormleerd[22341]: delete done
Jan 08 21:34:14 vps144761.ovh.net vormleerd[22341]: /home/raphael/vormleer/db.js:217
Jan 08 21:34:14 vps144761.ovh.net vormleerd[22341]: params.$name = conjugation[index][params.$person].toLocaleLowerCase(
Jan 08 21:34:14 vps144761.ovh.net vormleerd[22341]: ^
Jan 08 21:34:14 vps144761.ovh.net vormleerd[22341]: TypeError: Cannot read property 'toLocaleLowerCase' of undefined
Jan 08 21:34:14 vps144761.ovh.net vormleerd[22341]: at insertparamstx (/home/raphael/vormleer/db.js:217:58)
Jan 08 21:34:14 vps144761.ovh.net vormleerd[22341]: at Statement.<anonymous> (/home/raphael/vormleer/db.js:230:17)
Jan 08 21:34:14 vps144761.ovh.net systemd[1]: vormleerd.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by indriApollo** [comment]
```
`Jan 08 21:54:19 vps144761.ovh.net vormleerd[22530]: GET request for /verbs/conjugation/tegere/active/gerundium/none
Jan 08 21:54:27 vps144761.ovh.net vormleerd[22530]: POST request for /verbs/tegere
Jan 08 21:54:27 vps144761.ovh.net vormleerd[22530]: delete done
Jan 08 21:54:27 vps144761.ovh.net vormleerd[22530]: /home/raphael/vormleer/db.js:217
Jan 08 21:54:27 vps144761.ovh.net vormleerd[22530]: params.$name = conjugation[index][params.$person].toLocaleLowerCase(
Jan 08 21:54:27 vps144761.ovh.net vormleerd[22530]: ^
Jan 08 21:54:27 vps144761.ovh.net vormleerd[22530]: TypeError: Cannot read property 'toLocaleLowerCase' of undefined
Jan 08 21:54:27 vps144761.ovh.net vormleerd[22530]: at insertparamstx (/home/raphael/vormleer/db.js:217:58)
Jan 08 21:54:27 vps144761.ovh.net vormleerd[22530]: at Statement.<anonymous> (/home/raphael/vormleer/db.js:230:17)
```

**Comment by indriApollo** [comment]
Issue seems to be with the 'gerundium' property

**Comment by indriApollo** [comment]
Project is dead, wontfix.
